version: '3.6'
services:
  build:
    build: &build
      context: .
    volumes:
      - .:/output
    working_dir: /go/src/github.com/remind101/ssm-env

  test:
    build:
      <<: *build
    command: make test
